ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER app IDENTIFIED BY "AppUserPass123!"
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO app;